# Site settings
author: Dan Hwang
title: My Coding Journey
header-img: img/home-bg.png
email: danhwangfkpc@gmail.com
copyright_name: Dan Hwang
description: > # this means to ignore newlines until "baseurl:"
  From "Hello World" to Full-Stack Web Development
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  denhweng

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
